### ISSUE TITLE
node: WatchService tests are flaky on Mac

### ISSUE THREAD

**Issue by AviVahl** [wixplosives/file-services#32]
the tests sometimes expect outdated mtime.
event validation should re-query current mtime on each retry.

**Comment by AviVahl** [comment]
```
@file-services/node:   1) Node Watch Service
@file-services/node:        watching files
@file-services/node:          emits two different watch events when changes are >500ms appart:
@file-services/node:       AssertionError: expected [ Array(2) ] to deeply equal [ Array(2) ]
@file-services/node:       + expected - actual
@file-services/node:          {
@file-services/node:            "path": "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/temp-YQZoui/test-file"
@file-services/node:            "stats": {
@file-services/node:              "birthtime": 1573552551966
@file-services/node:       -      "mtime": 1573552552469
@file-services/node:       +      "mtime": 1573552551967
@file-services/node:            }
@file-services/node:          }
@file-services/node:          {
@file-services/node:            "path": "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/temp-YQZoui/test-file"
@file-services/node:       
@file-services/node:       at promise_assist_1.waitFor (/Users/runner/runners/2.160.2/work/file-services/file-services/packages/test-kit/src/watch-events-validator.ts:45:35)
@file-services/node:       at retry (/Users/runner/runners/2.160.2/work/file-services/file-services/node_modules/promise-assist/src/retry.ts:69:34)
@file-services/node: 
@file-services/node: error Command failed with exit code 1.
```
